# Generated by Django 5.1.7 on 2025-04-04 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_low_stock_threshold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['id']},
        ),
    ]
